FROM node:20-alpine AS builder
WORKDIR /app
ARG SERVICE
COPY package.json tsconfig.base.json ./
COPY packages ./packages
COPY services/${SERVICE} ./services/${SERVICE}
RUN npm install --workspace=@festix/shared --workspace=@festix/service-common --workspace=@festix/${SERVICE}
RUN npm run build -w @festix/shared -w @festix/service-common -w @festix/${SERVICE}

FROM node:20-alpine
WORKDIR /app
ARG SERVICE
ENV NODE_ENV=production
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/services/${SERVICE} ./services/${SERVICE}
COPY package.json ./
WORKDIR /app/services/${SERVICE}
EXPOSE 3000
CMD ["node", "dist/index.js"]
